[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_day_one"
path = "./chall_2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"


